### ISSUE TITLE
KeyError: 'past_k_time_interval'

### ISSUE THREAD

**Issue by Sunshine8921** [SizheWei/CoBEVFlow#2]
(cobevflow) aitest8@e6095bf2f947:~/wynne/CoBEVFlow$  python opencood/tools/train.py --hypes_yaml opencood/hypes_yaml/dair-v2x/npj/dair_where2comm_max_multiscale_resnet.yaml 
### Dataset Building ... ###
Irregular async dataset with past 1 frames and expectation time delay = 0 initialized! 1326 samples totally!
Irregular async dataset with past 1 frames and expectation time delay = 0 initialized! 486 samples totally!
/public/home/aitest8/anaconda3/envs/cobevflow/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
=== Time consumed: 0.0 minutes. ===
### Creating Model ... ###
device:  cuda
full path is:  /public/home/aitest8/wynne/CoBEVFlow/logs/logs/dair_where2comm_max_multiscale_resnet_2023_11_07_16_37_51
=== Time consumed: 0.1 minutes. ===
### Training start! ###
=== supervise_single_flag: True ===
learning rate 0.002000
/public/home/aitest8/anaconda3/envs/cobevflow/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
dict_keys(['object_bbx_center', 'object_bbx_mask', 'processed_lidar', 'record_len', 'label_dict', 'object_ids', 'pairwise_t_matrix', 'lidar_pose_clean', 'lidar_pose', 'avg_time_delay', 'cp_rate', 'single_object_label', 'object_bbx_center_single', 'object_bbx_mask_single', 'epoch'])
Traceback (most recent call last):
  File "opencood/tools/train.py", line 327, in <module>
    main()
  File "opencood/tools/train.py", line 219, in main
    ouput_dict = model(batch_data['ego'])
  File "/public/home/aitest8/anaconda3/envs/cobevflow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/aitest8/wynne/CoBEVFlow/opencood/models/point_pillar_where2comm_attn.py", line 245, in forward
    record_frames = data_dict['past_k_time_interval']                       #(B, )
KeyError: 'past_k_time_interval'

**Comment by W-E-A** [comment]
Same here: 

`### Dataset Building ... ###
Irregular async dataset with past 1 frames and expectation time delay = 0 initialized! 1326 samples totally!
Irregular async dataset with past 1 frames and expectation time delay = 0 initialized! 486 samples totally!
=== Time consumed: 0.0 minutes. ===
### Creating Model ... ###
device:  cuda
full path is:  ../logs/logs/dair_where2comm_max_multiscale_resnet_2023_11_27_15_18_54
=== Time consumed: 0.1 minutes. ===
### Training start! ###
=== supervise_single_flag: True ===
learning rate 0.002000
Traceback (most recent call last):
  File "opencood/tools/train.py", line 327, in <module>
    main()
  File "opencood/tools/train.py", line 219, in main
    ouput_dict = model(batch_data['ego'])
  File "/root/miniconda3/envs/w2c/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ai/volume/CoBEVFlow/opencood/models/point_pillar_where2comm_attn.py", line 244, in forward
    record_frames = data_dict['past_k_time_interval']                       #(B, )
KeyError: 'past_k_time_interval'`

**Comment by carrolltm** [comment]
when i use python tools/dataset_converter/dair2kitti.py --source-root ./data/DAIR-V2X/cooperative-vehicle-infrastructure/infrastructure-side \
    --target-root ./data/DAIR-V2X/cooperative-vehicle-infrastructure/infrastructure-side \
    --split-path ./data/split_datas/cooperative-split-data.json \
    --label-type lidar --sensor-view infrastructure --no-classmerge
python tools/dataset_converter/dair2kitti.py --source-root ./data/DAIR-V2X/cooperative-vehicle-infrastructure/vehicle-side \
    --target-root ./data/DAIR-V2X/cooperative-vehicle-infrastructure/vehicle-side \
    --split-path ./data/split_datas/cooperative-split-data.json \
    --label-type lidar --sensor-view vehicle --no-classmerge
to process DAIR-V2X。 and then i use the command "CUDA_VISIBLE_DEVICES=1 python opencood/tools/train.py --hypes_yaml opencood/hypes_yaml/dair-v2x/npj/dair_where2comm_max_multiscale_resnet.yaml", i alse meet the error about   KeyError: 'past_k_time_interval'`

**Comment by carrolltm** [comment]
when i use the yaml "opencood/hypes_yaml/dair-v2x/npj/dair_v2vnet.yaml", i not meet the errot about 'past_k_time_interval'`

**Comment by shifan-Z** [comment]
I encountered the same problem: KeyError: 'past_k_time_interval'. Did you manage to solve it?

**Comment by sunjingnjupt** [comment]
I’ve run into the same issue  about 'past_k_time_interval' —has anyone figured out a fix?
